# Generated by Django 5.2.7 on 2026-06-18 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_contactmessage_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pant',
            old_name='Title',
            new_name='title',
        ),
    ]
