from django.urls import path
from .import views 

urlpatterns = [
    path('',views.home_view, name = 'home'),
    path('login/',views.login_view, name ='login'),
    path('logout/',views.logout_view, name = 'logout'),
    path('register/',views.Register_view, name = 'register'),
    path('catergory/', views.catergoryView.as_view(), name='catergory'),
    path('protected/',views.protectedView.as_view(), name = 'protected'),
    path('home1/', views.home1View.as_view(), name = 'home1'),
    path('contact/', views.contact_view, name='contact'),
    path('home/',views.home_view, name='home3'),
    path('downloaded-books/', views.downloadedBooksView.as_view(), name='downloaded_books'),
    path('download-pdf/<path:book_key>/', views.download_pdf, name='download_pdf'),
    path('toggle-favourite/<path:book_key>/', views.toggle_favourite, name='toggle_favourite'),
    path('toggle-bookmark/<path:book_key>/', views.toggle_bookmark, name='toggle_bookmark'),
    path('library-status/', views.get_user_library_status, name='library_status'),
    path('my-favourites/', views.get_user_favourites, name='my_favourites'),
    path('my-bookmarks/', views.get_user_bookmarks, name='my_bookmarks'),
    path('my-recent/', views.get_user_recent, name='my_recent'),
    path('mark-viewed/<path:book_key>/', views.mark_book_viewed, name='mark_viewed'),
    path('remove-download/<path:book_key>/', views.remove_download, name='remove_download'),
    path('record-download/<path:book_key>/', views.record_download, name='record_download'),
    path('read-book/<path:book_key>/', views.read_book, name='read_book'),
    path('rate-book/<path:book_key>/', views.rate_book, name='rate_book'),
    path('book-ratings/<path:book_key>/', views.get_book_ratings, name='book_ratings'),
    path('recommendations/', views.get_recommendations, name='recommendations'),
    path('summarize/<path:book_key>/', views.summarize_book, name='summarize_book'),
    path('dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('course-materials/', views.course_materials, name='course_materials'),
    path('upload-material/', views.upload_material, name='upload_material'),
    path('request-access/<int:material_id>/', views.request_access, name='request_access'),
    path('approve-access/<int:access_id>/', views.approve_access, name='approve_access'),
    path('view-material/<int:material_id>/', views.view_material, name='view_material'),
    path('lecturer-dashboard/', views.lecturer_dashboard, name='lecturer_dashboard'),
    path('become-lecturer/', views.become_lecturer, name='become_lecturer'),
    path('delete-material/<int:material_id>/', views.delete_material, name='delete_material'),
    path('fetch-book-text/', views.fetch_book_text, name='fetch_book_text'),
]
